markdown: kramdown
kramdown:
  input: GFM # Enables GitHub-Flavored Markdown

# Site-wide variables available to all pages via the `site` variable, ex: `{{ site.github_url }}`
github_url: https://github.com/block/elasticgraph
x_url: https://x.com/elasticgraph
x_username: "@ElasticGraph"
support_email: elasticgraph@squareup.com
tagline: Schema-driven, scalable, cloud-native, batteries-included GraphQL with superpowers.
description: ElasticGraph is an open-source framework for indexing, searching, and aggregating data powered by GraphQL and OpenSearch.

# Reusable CSS styling for the site, available via the `site.style` variable, ex: `{{ site.style.body }}`
style:
  body: bg-gray-50 dark:bg-gray-900 text-gray-900 dark:text-gray-100 flex flex-col h-screen
  link: text-blue-600 dark:text-blue-400 hover:underline
